name: trippify
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  material_symbols_icons: ^4.2801.1
  scrollable_clean_calendar: ^1.5.0
  table_calendar: ^3.1.3
  intl: 0.20.2
  timelines_plus: ^1.0.6
  image_picker: ^1.1.2
  flutter_dotenv: ^5.2.1
  flutter_bloc: ^9.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_svg: ^2.2.0
  smooth_page_indicator: ^1.2.1
  flutter_multi_select_items: ^0.4.3
  firebase_auth: ^5.6.2
  firebase_core: ^3.15.1
  cloud_firestore: ^5.6.11
  go_router: ^16.0.0
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.13

flutter:

  uses-material-design: true

  assets:
  - assets/icons/
  - assets/images/
  - .env